services:
  - type: web
    name: anipalengke
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r src/code/requirements.txt"
    startCommand: "cd src/code && python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
    secretFiles:
      - key: FIREBASE_SERVICE_ACCOUNT
        mountPath: /etc/secrets/serviceAccountKey.json
